change default site_status to all
NOAA-OWP/evaluation_tools pull request #12
Opened 2021-01-05 21:47 UTC by hellkite500

The client defaults to fetching only "active" status gage data.  By default, the NWIS rest API uses "all" as the default parameter.  When retrieving historical data, this causes a bit of a surprise when a gage comes back with no data.

## Changes

- Change default `site_status` from `active` to `all`

## Checklist

- [x] PR has an informative and human-readable title
- [x] PR is well outlined and documented. See [#12](https://github.com/jarq6c/evaluation_tools/pull/12) for an example
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows project standards (see [CONTRIBUTING.md](../CONTRIBUTING.md))
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output) using [numpy docstring](https://numpydoc.readthedocs.io/en/latest/format.html) formatting
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

2021-01-05 21:53 UTC, aaraney requested changes
This will only change the behavior for `get`. The same behavior will be seen in all other `get_` variants. Due to how python handles documentation type hints, it was required to include the `siteStatus` keyword parameter in each of the methods. As such, they should all be changed to `"all"` for consistency.

2021-01-05 22:34 UTC, aaraney approved these changes
Look great! Thanks @hellkite500

2021-01-06 13:19 UTC, aaraney commented
We should probably move the minor version of the package up after this change. The change is sufficiently large to do so. Ill commit this change to this branch.

2021-01-06 13:25 UTC, jarq6c approved these changes
Looks good to me.

2021-01-06 13:26 UTC, merged