Add Metrics Subpackage
NOAA-OWP/evaluation_tools pull request #29
Opened 2021-02-02 13:48 UTC by jarq6c

Evaluation workflows will compute standard metrics. This subpackage adds several common categorical metrics used in forecast verification.

## Additions

- New `evaluation_tools.metrics` subpackage

## Removals

- None

## Changes

- Update README.md list of packages, examples, and installation instructions.

## Testing

1. All metrics have unit tests.

## Notes

- Future metrics should be housed in this package. Additional categorical metrics should inherent the general form, inputs, and outputs of the existing categorical metrics.
- Closes #28 

## Todos

- Add continuous metrics like NSE/NNSE, Pearson correlation, KGE, etc. Some of these may introduce a `scipy` dependence.
- Update sphinx docs

## Checklist

- [x] PR has an informative and human-readable title
- [x] PR is well outlined and documented. See [#12](https://github.com/jarq6c/evaluation_tools/pull/12) for an example
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows project standards (see [CONTRIBUTING.md](../CONTRIBUTING.md))
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output) using [numpy docstring](https://numpydoc.readthedocs.io/en/latest/format.html) formatting
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

2021-02-02 19:27 UTC, aaraney requested changes
Looks great! These are some great additions to the toolbox! Only a few minor copy paste changes that I see. Great stuff as always.

2021-02-02 19:27 UTC, aaraney commented on python/metrics/evaluation_tools/metrics/metrics.py
> +def probability_of_detection(
Wouldn't hurt to add `true_positive_key` and `false_negative_key` as keyword args with default values. I think that would help make the method intention more clear.

2021-02-02 19:27 UTC, aaraney commented on python/metrics/evaluation_tools/metrics/metrics.py
> +def probability_of_false_detection(
Same as above

2021-02-02 19:27 UTC, aaraney commented on python/metrics/evaluation_tools/metrics/metrics.py
> +def probability_of_false_alarm(
Same as above

2021-02-02 19:27 UTC, aaraney commented on python/metrics/evaluation_tools/metrics/metrics.py
> +def threat_score(
Same as above

2021-02-02 19:27 UTC, aaraney commented on python/metrics/evaluation_tools/metrics/metrics.py
> +def frequency_bias(
Same as above

2021-02-02 19:27 UTC, aaraney commented on python/metrics/evaluation_tools/metrics/metrics.py
> +def percent_correct(
Same as above

2021-02-02 19:27 UTC, aaraney commented on python/metrics/evaluation_tools/metrics/metrics.py
> +def base_chance(
You guessed it, same as above

2021-02-02 19:27 UTC, aaraney commented on python/metrics/evaluation_tools/metrics/metrics.py
> +def equitable_threat_score(
To round it all out, same as above

2021-02-02 19:28 UTC, jarq6c commented
Working on updating this branch given new sphinx guide.

2021-02-03 14:46 UTC, aaraney approved these changes
Thanks for pushing a few changes plus adding the sphinx docs!

2021-02-03 14:46 UTC, aaraney commented on docs/evaluation_tools.metrics.rst
> +evaluation\_tools.metrics package
should be `subpackage` instead of `package`. I pushed up a change.

2021-02-03 14:46 UTC, aaraney commented on python/metrics/evaluation_tools/metrics/metrics.py
> +"""
This looks great!

2021-02-03 14:46 UTC, merged